# Generated by Django 4.1.3 on 2022-12-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audiens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuantitas", models.CharField(max_length=50, verbose_name="audiens")),
            ],
        ),
        migrations.CreateModel(
            name="Ruangan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruangan", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_pemesan",
                    models.CharField(max_length=100, verbose_name="Nama Pemesan"),
                ),
                (
                    "email_pemesan",
                    models.EmailField(max_length=254, verbose_name="Email Pemesan"),
                ),
                (
                    "telepon_pemesan",
                    models.CharField(max_length=50, verbose_name="Telepon/WA"),
                ),
                ("tanggal_acara", models.DateField(verbose_name="Tanggal Acara")),
                ("waktu_acara", models.TimeField(verbose_name="Waktu Acara")),
                ("acara", models.CharField(max_length=100)),
                ("keterangan", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audiens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.audiens",
                    ),
                ),
                (
                    "ruangan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.ruangan",
                    ),
                ),
            ],
        ),
    ]
