# Generated by Django 4.1.3 on 2022-12-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audiens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuantitas", models.CharField(max_length=50, verbose_name="audiens")),
            ],
        ),
        migrations.CreateModel(
            name="Ruangan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ruangan", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WaktuPemesanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waktu",
                    models.CharField(max_length=50, verbose_name="Waktu Pemesanan"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, verbose_name="Nama Pemesan")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Pemesan"),
                ),
                ("telepon", models.CharField(max_length=50, verbose_name="Telepon/WA")),
                ("acara", models.CharField(max_length=100)),
                ("tanggal_pemesanan", models.DateField(verbose_name="Tanggal Acara")),
                ("keterangan", models.TextField()),
                ("konfirmasi", models.BooleanField(default=False)),
                ("selesai", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audiens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.audiens",
                    ),
                ),
                (
                    "ruangan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.ruangan",
                    ),
                ),
                (
                    "waktu_pemesanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.waktupemesanan",
                    ),
                ),
            ],
        ),
    ]
