# Generated by Django 4.1.3 on 2022-12-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="waktu_pemesanan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.waktupemesanan",
                verbose_name="Waktu Acara",
            ),
        ),
    ]
