# Generated by Django 4.1.3 on 2022-12-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaktuPemesanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waktu",
                    models.CharField(max_length=50, verbose_name="Waktu Pemesanan"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="reservation",
            name="waktu_pemesanan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation.waktupemesanan",
            ),
        ),
    ]
