# Generated by Django 4.1.3 on 2022-12-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="tanggal_acara",
            new_name="tanggal_pemesanan",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="waktu_acara",
            new_name="waktu_pemesanan",
        ),
    ]
