# Generated by Django 4.1.3 on 2022-12-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0002_rename_tanggal_acara_reservation_tanggal_pemesanan_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="email_pemesan",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="nama_pemesan",
            new_name="nama",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="telepon_pemesan",
            new_name="telepon",
        ),
    ]
