# Generated by Django 4.1.3 on 2022-12-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_rename_email_pemesan_reservation_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="konfirmasi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="selesai",
            field=models.BooleanField(default=False),
        ),
    ]
